Merge origin/14.04 and add room alias support

diff --git a/debian/matrix-gateway.postinst b/debian/matrix-gateway.postinst
--- a/debian/matrix-gateway.postinst
+++ b/debian/matrix-gateway.postinst
@@ -1,6 +1,6 @@
-#!/bin/bash
+#!/bin/sh
 
-# @file poll_sprout.sh
+# @file matrix-gateway.postinst
 #
 # Project Clearwater - IMS in the Cloud
 # Copyright (C) 2014  Metaswitch Networks Ltd
@@ -34,29 +34,39 @@
 # under which the OpenSSL Project distributes the OpenSSL toolkit software,
 # as those licenses appear in the file LICENSE-OPENSSL.
 
-# This script uses a SIP message to poll a process and check whether it is
-# healthy.
+#
+# see: dh_installdeb(1)
 
-# In case sprout has only just restarted, give it a few seconds to come up
-sleep 5
+set -e
 
-# Read the config, defaulting appropriately.
-scscf=5054
-icscf=0
-. /etc/clearwater/config
-[ -z $signaling_namespace ] || namespace_prefix="ip netns exec $signaling_namespace"
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-# If we have S-CSCF configured, check it.
-rc=0
-if [ "$scscf" != "0" ] ; then
-  $namespace_prefix /usr/share/clearwater/bin/poll-sip $scscf
-  rc=$?
-fi
+case "$1" in
+    configure)
+        # Restart sprout to force reload of new plug-in.  Always do this by
+        # terminating sprout so monit will restart it more-or-less immediately.
+        # (monit restart seems to have significant lag.)
+        # Don't fail if it's already stopped.
+        service sprout stop || /bin/true
+    ;;
 
-# If that succeeded and we have I-CSCF configured, check it.
-if [ $rc = 0 ] && [ "$icscf" != "0" ] ; then
-  $namespace_prefix /usr/share/clearwater/bin/poll-sip $icscf
-  rc=$?
-fi
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
 
-exit $rc
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+exit 0
diff --git a/debian/matrix-gateway.prerm b/debian/matrix-gateway.prerm
--- a/debian/matrix-gateway.prerm
+++ b/debian/matrix-gateway.prerm
@@ -1,6 +1,6 @@
-#!/bin/bash
+#!/bin/sh
 
-# @file poll_restund.sh
+# @file matrix-gateway.prerm
 #
 # Project Clearwater - IMS in the Cloud
 # Copyright (C) 2014  Metaswitch Networks Ltd
@@ -34,27 +34,33 @@
 # under which the OpenSSL Project distributes the OpenSSL toolkit software,
 # as those licenses appear in the file LICENSE-OPENSSL.
 
-# This script uses a STUN message to poll restund and check whether it is
-# healthy.
+#
+# see: dh_installdeb(1)
 
-# Read the config, defaulting appropriately.
-. /etc/clearwater/config
+set -e
 
-# Send the STUN message.  The nc line also includes checking the first line of the response starts
-# "\x01\x01" - a positive response.
-# The -q option forces netcat to quit after 1 second. This works
-# around a netcat bug where it tight-loops forever if the UDP port
-# it's trying to contact is closed.
-printf '\x00\x01\x00\x00\x21\x12\xa4\x42MonitPollXid' |
-nc -v -C -u -w 2 -q 1 $local_ip 3478 2> /tmp/poll_restund.sh.nc.stderr.$$ | tee /tmp/poll_restund.sh.nc.stdout.$$ | head -1 | grep -U -P -q '^\x01\x01'
-rc=$?
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-# Check the return code and log if appropriate
-if [ $rc != 0 ] ; then
-  echo STUN poll failed to $local_ip    >&2
-  cat /tmp/poll_restund.sh.nc.stderr.$$ >&2
-  cat /tmp/poll_restund.sh.nc.stdout.$$ >&2
-fi
-rm -f /tmp/poll_restund.sh.nc.stderr.$$ /tmp/poll_restund.sh.nc.stdout.$$
+case "$1" in
+    remove|upgrade|deconfigure)
+    ;;
 
-exit $rc
+    failed-upgrade)
+    ;;
+
+    *)
+        echo "prerm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+exit 0
